name = "agent-worker"
main = "src/worker.ts"
compatibility_date = "2025-08-28"


# Bindings
[[d1_databases]]
binding = "DB"
database_name = "agent-db"
database_id = ""


[[kv_namespaces]]
binding = "AGENT_KV"
id = ""

script_name = "agent-worker"
